=== ArtemJDev/frameworks-etc/web/src/main/java/xmltest/countryXSDv2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--XSD описание xml, xsd- клаасс, а xml конкретный объект-->
<!--схема к конкретному xml формату-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--описываем элемент root, rootType - комплексный тип внутри которго countryType,элементы с именем country-->
  <xs:element name="root" type="rootType"/>
  <!--   complextype описываем сцущности внутри maxOccurs - бесконечно вхожденеи + минимально -->
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="countryType">
    <!--    без подробностей вложения   type="xs:string" -->
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="capital" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="visa_cost" type="xs:double"/>
    </xs:sequence>
    <!--    описание атррибута countrty , optional - можем исполтьзовать можем не использовать, required -->
    <xs:attribute type="xs:string" name="contryCode" use="optional"/>
  </xs:complexType>

  <xs:complexType name="visa_cost">
    <xs:simpleContent>
      <xs:extension base="xs:double">
        <xs:attribute name="code" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>



</xs:schema>

=== ArtemJDev/frameworks-etc/web/src/main/xmlpack/xmltest/country2XSDv2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--ссылаемся на наш xsd, xml фал будет являться экземпляром определенной схемы-->
<root xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation ="countryXSDv2.xsd"
>
  <country contryCode="ua">
    <name>Ukraine</name>
    <capital>Kiev</capital>
    <description>Ukraine is..</description>
    <visa_cost>344</visa_cost>
  </country>
  
  <country contryCode="ru">
    <name>Russia</name>
    <capital>Moscow</capital>
    <description>Russia is..</description>
    <visa_cost>555</visa_cost>
  </country>

</root>
