<?xml version="1.0" encoding="UTF-8" ?>
<!--DTD правила описания ml  документа-->
<!--1 К порневой элемент root -->
<!--2 внутри которого могут быть только country * повторение >1 -->
<!--3 сожержится внутри country или ли иил -->
<!--4 ATTLIST аттирбут внутри country CDDATA(данныее) REQUIRED - обязательный #IMPLIED - по желанию -->
<!--5 6 7 описываем теги внутри формат PCDATA - только текст -->
<!DOCTYPE root [
  <!ELEMENT root (country)*>
  <!ELEMENT country (name|capital|description)*>
  <!ATTLIST country contryCode CDATA #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT capital (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  ]>

<root>
  <country contryCode="ua">
    <name>Ukraine</name>
    <capital>Kiev</capital>
    <description>Ukraine is..</description>
  </country>
  
  <country contryCode="ru">
    <name>Russia</name>
    <capital>Moscow</capital>
    <description>Russia is..</description>
  </country>

</root>

