=== ArtemJDev/frameworks-etc/web/src/main/xmlpack/xmltest/countryXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--XSD описание xml, xsd- клаасс, а xml конкретный объект-->
<!--схема к конкретному xml формату-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--описываем элемент root, rootType - комплексный тип внутри которго countryType,элементы с именем country-->
  <xs:element name="root" type="rootType"/>

  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="countryType">
    <!--    сухности комплексного типа  -->
    <xs:sequence>

      <xs:element name="name">
<!--    простой тип  simpleType  -->
        <xs:simpleType>
          <!--    тип STRING  -->
          <xs:restriction base="xs:string">
            <!--    внутри него  -->
            <xs:enumeration value="Ukraine"/>
            <xs:enumeration value="Russia"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="capital">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Kiev"/>
            <xs:enumeration value="Moscow"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="description">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ukraine is.."/>
            <xs:enumeration value="Russia is.."/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

    </xs:sequence>
    <!--    описание атррибута countrty , optional - можем исполтьзовать можем не использовать, required -->
    <xs:attribute type="xs:string" name="contryCode" use="optional"/>
  </xs:complexType>

</xs:schema>

=== ArtemJDev/frameworks-etc/web/src/main/xmlpack/xmltest/country2XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--ссылаемся на наш xsd, xml фал будет являться экземпляром определенной схемы-->
<root xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation ="countryXSD.xsd"
>
  <country contryCode="ua">
    <name>Ukraine</name>
    <capital>Kiev</capital>
    <description>Ukraine is..</description>
  </country>
  
  <country contryCode="ru">
    <name>Russia</name>
    <capital>Moscow</capital>
    <description>Russia is..</description>
  </country>

</root>
