=== ArtemJDev/frameworks-etc/XML/XSD/letter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="letter">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element name="name" type="xsd:token"></xsd:element>
				<xsd:element name="id" type="xsd:long"></xsd:element>
				<xsd:sequence maxOccurs="unbounded">
					<xsd:element name="title" type="xsd:token"></xsd:element>
					<xsd:element name="count" type="xsd:int"></xsd:element>
				</xsd:sequence>
				<xsd:element name="total" type="xsd:double"></xsd:element>
				<xsd:element name="currency" type="xsd:token"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== ArtemJDev/frameworks-etc/xml-practise/XSD/letter.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="letter.xslt"?>

<letter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="letter.xsd">Уважаемый(ая) <name>Пупкин</name>
Ваш заказ: <id>123</id>.
<title>Java XML test</title> - <count>1</count>
<title>Java XML test</title> - <count>1</count>
<title>Java XML test</title> - <count>1</count>
<title>Java XML test</title> - <count>1</count>
Стоимость заказа: <total>200</total><currency> грн.</currency>
</letter>
